services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./config.py:/app/config.py:ro
      - ./requirements.txt:/app/requirements.txt:ro
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8001:80"
    depends_on:
      - backend
    restart: unless-stopped
